name: Compile Tailwind CSS

on:
  workflow_dispatch:  # Manually trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify Node.js version

      # Install NPM dependencies
      - name: Install Dependencies
        run: npm install

      # Compile Tailwind CSS
      - name: Compile Tailwind CSS
        run: npx tailwindcss build -i ./base-tw.css -o ./out/output.css  # Set your specific paths

      # Auto-commit the compiled Tailwind CSS
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Github Action: Tailwind files"
          branch: ${{ github.ref }}
